### ISSUE TITLE
[note] Reference codec implementations

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/cram-js#44]
https://github.com/jkbonfield/htscodecs/tree/master/javascript

**Comment by jkbonfield** [comment]
See https://github.com/GMOD/cram-js/pull/68 for my attempt at this.

Note I'm a novice when it comes to JS so the actual reference implementations probably aren't pretty.   I wasn't really intending originally to use them either, but I wanted a simple language  without lots of unnecessary syntax (required types, etc) so the pseudocode in the spec could match an implementation as close as possible in order to spot spec errors.  JavaScript fitted the bill and turned out to be surprisingly OK for performance.

**Comment by rbuels** [comment]
Very cool! Setting this to "closed", let's see if we can get these in use in #68
